#!/bin/bash

set -e

SCRIPT_DIR="/tmp"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    -- CREATE USER $POSTGRES_USER WITH PASSWORD '$POSTGRES_PASSWORD';
    -- CREATE DATABASE $POSTGRES_DB;
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $POSTGRES_USER;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -a -f $SCRIPT_DIR/app_db.sql

