-- Database generated with pgModeler (PostgreSQL Database Modeler).
-- pgModeler version: 1.1.0-alpha
-- PostgreSQL version: 15.0
-- Project Site: pgmodeler.io
-- Model Author: ---
-- -- object: app | type: ROLE --
-- -- DROP ROLE IF EXISTS app;
-- CREATE ROLE app WITH 
-- 	SUPERUSER
-- 	CREATEDB
-- 	CREATEROLE
-- 	INHERIT
-- 	LOGIN
-- 	REPLICATION
-- 	BYPASSRLS
-- 	 PASSWORD '********';
-- -- ddl-end --
-- 

-- Database creation must be performed outside a multi lined SQL file. 
-- These commands were put in this file only as a convenience.
-- 
-- object: app | type: DATABASE --
-- DROP DATABASE IF EXISTS app;
CREATE DATABASE app
	ENCODING = 'UTF8'
	LC_COLLATE = 'en_US.utf8'
	LC_CTYPE = 'en_US.utf8'
	TABLESPACE = pg_default
	OWNER = app;
-- ddl-end --


-- object: app_sch | type: SCHEMA --
-- DROP SCHEMA IF EXISTS app_sch CASCADE;
CREATE SCHEMA app_sch;
-- ddl-end --
ALTER SCHEMA app_sch OWNER TO app;
-- ddl-end --

SET search_path TO pg_catalog,public,app_sch;
-- ddl-end --

-- object: app_sch."user" | type: TABLE --
-- DROP TABLE IF EXISTS app_sch."user" CASCADE;
CREATE TABLE app_sch."user" (
	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 0 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1 ),
	email text NOT NULL,
	name text,
	surname text,
	mobile text,
	CONSTRAINT user_pk PRIMARY KEY (email)
);
-- ddl-end --
ALTER TABLE app_sch."user" OWNER TO app;
-- ddl-end --
